class AlertNotFoundError(Exception):
    pass

class UserNotFoundError(Exception):
    pass